import {
  StatusCellRenderer,
  RatingCellRenderer,
  SkillsCellRenderer,
  SalaryCellRenderer,
} from "./cellRenderers";

export const getColumnDefs = () => [
  {
    field: "id",
    headerName: "ID",
    width: 80,
    filter: "agNumberColumnFilter",
    checkboxSelection: true,
    headerCheckboxSelection: true,
    pinned: "left",
  },
  {
    field: "firstName",
    headerName: "First Name",
    width: 120,
    filter: "agTextColumnFilter",
    editable: true,
  },
  {
    field: "lastName",
    headerName: "Last Name",
    filter: "agTextColumnFilter",
    width: 120,
    editable: true,
  },
  {
    field: "email",
    headerName: "Email",
    width: 250,
    filter: "agTextColumnFilter",
  },
  {
    field: "department",
    headerName: "Department",
    filter: "agSetColumnFilter",
    editable: true,
  },
  {
    field: "position",
    headerName: "Position",
    width: 200,
    filter: "agTextColumnFilter",
  },
  {
    field: "salary",
    headerName: "Salary",
    filter: "agNumberColumnFilter",
    cellRenderer: SalaryCellRenderer,
    editable: true,
    width: 130,
  },
  {
    field: "hireDate",
    headerName: "Hire Date",
    filter: "agDateColumnFilter",
    width: 130,
  },
  {
    field: "age",
    headerName: "Age",
    filter: "agNumberColumnFilter",
    width: 90,
  },
  {
    field: "location",
    headerName: "Location",
    filter: "agSetColumnFilter",
    editable: true,
    width: 140,
  },
  {
    field: "performanceRating",
    headerName: "Performance",
    cellRenderer: RatingCellRenderer,
    // filter: "agNumberColumnFilter",
    width: 180,
  },
  {
    field: "projectsCompleted",
    headerName: "Projects",
    filter: "agNumberColumnFilter",
    width: 120,
  },
  {
    field: "isActive",
    headerName: "Status",
    cellRenderer: StatusCellRenderer,
    filter: "agSetColumnFilter",
    width: 110,
  },
  {
    field: "skills",
    headerName: "Skills",
    cellRenderer: SkillsCellRenderer,
    filter: false,
    width: 280,
    autoHeight: true,
  },
  {
    field: "manager",
    headerName: "Manager",
    filter: "agSetColumnFilter",
    width: 160,
  },
];
